version: '3'
services:
  database:
    image: mysql:8.0
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurant_management_test
      MYSQL_USER: vardhaman
      MYSQL_PASSWORD: mypass
    networks:
      - internal

  server:
    build:
      context: .
      dockerfile: ./Dockerfile_test
    restart: on-failure
    ports:
      - 4000:4000
    depends_on:
      - database
    networks:
      - internal
networks:
  internal:
    driver: "bridge"
