FROM golang:1.12-alpine
RUN set -ex; \
    apk update; \
    apk add --no-cache git
WORKDIR /go/src/github.com/vds/go-resman/
ENV GO111MODULE=on
COPY ./ ./
RUN go mod download
RUN go mod verify
RUN go clean github.com/vds/go-resman
CMD CGO_ENABLED=0 go test ./cmd/
